name: Firebog Hosts list collector
on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  trophy:
    name: Update latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Collect latest hosts file
        continue-on-error: true
        run: |
          wget -U "${UA}" -O "./hosts/firebog/tick.txt" "https://v.firebog.net/hosts/lists.php?type=tick"
          wget -U "${UA}" -O "./hosts/firebog/aio" -i "./hosts/firebog/tick.txt"
      - name: Commit
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "${{github.workflow}} (${{github.run_number}}/${{github.run_id}})"
            git push
          else
            echo "nothing to commit"
            exit 0
          fi