name: Firebog List Collector
on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  trophy:
    name: Update latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Collect latest hosts file
        run: |
          (wget -qO- "https://v.firebog.net/hosts/static/w3kbl.txt"; echo) > ./hosts/firebog/suspicious
          (wget -qO- "https://v.firebog.net/hosts/AdguardDNS.txt"; echo) > ./hosts/firebog/ads
          (wget -qO- "https://v.firebog.net/hosts/Admiral.txt"; echo) >> ./hosts/firebog/ads
          (wget -qO- "https://v.firebog.net/hosts/Easylist.txt"; echo) >> ./hosts/firebog/ads
          (wget -qO- "https://v.firebog.net/hosts/Easyprivacy.txt"; echo) > ./hosts/firebog/trackers
          (wget -qO- "https://v.firebog.net/hosts/Prigent-Ads.txt"; echo) >> ./hosts/firebog/trackers
          (wget -qO- "https://v.firebog.net/hosts/RPiList-Malware.txt"; echo) > ./hosts/firebog/malicious
          (wget -qO- "https://v.firebog.net/hosts/RPiList-Phishing.txt"; echo) >> ./hosts/firebog/malicious

      - name: Commit
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "${{github.workflow}} (${{github.run_number}}/${{github.run_id}})"
            git push
          else
            echo "nothing to commit"
            exit 0
          fi
