name: Steven Black List Collector
on:
  schedule:
    - cron: '10 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  trophy:
    name: Update latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Collect latest hosts file
        run: |
          wget -U "${UA}" -O "./hosts/steven-black/unified" "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/fake-news" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-only/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/gambling" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/porn" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/social" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social-only/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/all" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts"
          wget -U "${UA}" -O "./hosts/steven-black/non-unified" "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social-only/hosts"
      - name: Commit
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "${{github.workflow}} (${{github.run_number}}/${{github.run_id}})"
            git push
          else
            echo "nothing to commit"
            exit 0
          fi